import { AlertModal } from "@/components/alert-modal/AlertModal";
import { CompositionRoot } from "@/components/composition-root/CompositionRoot";
import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const vazir = localFont({ src: "./Vazir.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={vazir.className}>
        <ReactQueryProvider>
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          <CompositionRoot />
          <AlertModal />
          <Toaster />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
