import ReactQueryProvider from "@/providers/ReactQueryProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CompositionRoot } from "@/components/composition-root/CompositionRoot";
import { AlertModal } from "@/components/alert-modal/AlertModal";

const vazir = localFont({ src: "./Vazir.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazir.className}>
        <ReactQueryProvider>
          <CompositionRoot />
          <AlertModal />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
